final Map<String, String> leagues = {
  '32': 'assets/leagues/CUP-BLUE-Photoroom.png-Photoroom.png',
  '34': 'assets/leagues/Enterprise-Cup (1).png',
  '109': 'assets/leagues/Enterprise-Cup (1).png',
  '111': 'assets/leagues/Rugby Super Series.png',
  "1": 'assets/leagues/fkf-premier-league.png',
  '100': 'assets/leagues/Kenya_Cup_logo.png',
  '90': 'assets/leagues/Kenya_Cup_logo.png',
  '31': 'assets/leagues/Kenya_Cup_logo.png'
};

final Map<String, String> rugbyImages = {
  '166': 'assets/rugby/blak blad.png',
  '1044': 'assets/rugby/Buffaloes.PNG',
  '1046': 'assets/rugby/Cheetahs.PNG',
  '812': 'assets/rugby/Dkfv4aSW0AAR1hB.png',
  '416': 'assets/rugby/Dkfv4aSW0AAR1hB.png',
  '459': 'assets/rugby/Dkfv4aSW0AAR1hB.png',
  '171': 'assets/rugby/Impala.png',
  '618': 'assets/rugby/Impala.png',
  '800': 'assets/rugby/Impala.png',
  '603': 'assets/rugby/Impala.png',
  '824': 'assets/rugby/JKUAT.png',
  '620': 'assets/rugby/JKUAT.png',
  '578': 'assets/rugby/JKUAT.png',
  '832': 'assets/rugby/kabras.png',
  '797': 'assets/rugby/kabras.png',
  '462': 'assets/rugby/kabras.png',
  '243': 'assets/rugby/kabras.png',
  '469': 'assets/rugby/KCB.png',
  '172': 'assets/rugby/KCB.png',
  '1045': 'assets/rugby/Lions.PNG',
  '163': 'assets/rugby/Meanmachinerfclogo.png',
  '626': 'assets/rugby/Meanmachinerfclogo.png',
  '798': 'assets/rugby/Meanmachinerfclogo.png',
  '458': 'assets/rugby/Nondescripts.png',
  '675': 'assets/rugby/Nondescripts.png',
  '616': 'assets/rugby/Oilers.png',
  '703': 'assets/rugby/Oilers.png',
  '869': 'assets/rugby/Oilers.png',
  '169': 'assets/rugby/Oilers.png',
  '702': 'assets/rugby/Quins.png',
  '613': 'assets/rugby/Quins.png',
  '605': 'assets/rugby/Quins.png',
  '471': 'assets/rugby/Quins.png',
  '1043': 'assets/rugby/Rhinos.PNG',
  '585': 'assets/rugby/Rhinos.PNG',
  '820': 'assets/rugby/SC Pirates.png',
  '819': 'assets/rugby/trans-falcons.png',
  '461': 'assets/rugby/trans-falcons.png',
  '162': 'assets/rugby/trans-falcons.png',
  '159': 'assets/rugby/trans-falcons.png',
  '899': 'assets/rugby/Western Bulls (2).png',
  '466': 'assets/rugby/Western Bulls (2).png',
  '481': 'assets/rugby/blak blad.png',
  '898': 'assets/rugby/blak blad.png',
  '1285': 'assets/rugby/JKUAT.png',
  '1158': 'assets/rugby/JKUAT.png',
  '881': 'assets/rugby/JKUAT.png',
  '1284': 'assets/rugby/Zetech Oaks.png',
  '1286': 'assets/rugby/SC Pirates.png',
  '1287': 'assets/rugby/TUM Marines (1).png',
  '532': 'assets/rugby/Impala.png',
  '533': 'assets/rugby/Impala.png',
  '571': 'assets/rugby/Impala.png',
  '823': 'assets/rugby/Impala.png',
  "465": 'assets/rugby/Homeboyz.png',
  "475": 'assets/rugby/Catholic Monks Logo.png',
  "420": 'assets/rugby/Nakuru RFC.png',
  "464": 'assets/rugby/Kisumu_Rugby_Football_Club_Logo.jpg',
  "408": 'assets/rugby/Strathmore Leos.png',
  "474": 'assets/rugby/Mwamba RFC.png',
  "468": 'assets/rugby/Oilers.png',
  "558": 'assets/rugby/UoE Trojans.png',
  "472": 'assets/rugby/Quins.png',
  '762': 'assets/rugby/Kabete Stallions.png',
  '1159': 'assets/rugby/Kabete Stallions.png',
  '1257': 'assets/rugby/Kabete Stallions.png',
  "1648": "assets/uganda/Buffaloes.png",
  "1653": "assets/uganda/Elgon Wolves 7s.png",
  "1656": "assets/uganda/Heathens 7s.png",
  "1657": "assets/uganda/Hippos 7s.png",
  "1655": "assets/uganda/Impis 7s.png",
  "1652": "assets/uganda/Kobs.png",
  "1651": "assets/uganda/Mongers.png",
  "1660": "assets/uganda/Pirates Rugby.png",
  "1661": "assets/uganda/Rams 7s.png",
  "1647": "assets/uganda/Rhinos 7s.png",
  "1688": "assets/uganda/Titans 7s.png",
  "1715": "assets/uganda/Titans 7s.png",
  "1659": "assets/uganda/Walukuba.png",
  "1649": "assets/uganda/Warriors 7s.png",
  "1713": "assets/uganda/Mustangs.png",
  "1711": "assets/uganda/Silverbacks 7s.png",
  "1712": "assets/uganda/Buddu 7s.png",
};

final Map<String, String> footballImages = {
  "979": "assets/football/Bondo United.png",
  "612": "assets/football/Bungoma Queens.jpg",
  "1009": "assets/football/Bungoma Queens.jpg",
  "1035": "assets/football/COMPEL FC.png",
  "183": "assets/football/Kayole Starlets.jpg",
  "494": "assets/football/KENYA PRISONS.png",
  "477": "assets/football/Kibarage Sportiff (1).png",
  "307": "assets/football/Kings Football Academy.png",
  "1141": "assets/football/KIRIGITI.png",
  "291": "assets/football/KISPED.jpg",
  "111": "assets/football/KSG.png",
  "787": "assets/football/MAKARIOS.png",
  "438": "assets/football/MathareUnited.png",
  "18": "assets/football/MathareUnited.png",
  "1056": "assets/football/Mombasa olympic Ladies.png",
  "699": "assets/football/Mombasa Stars.jpg",
  "127": "assets/football/NAIROBI UNITED.png",
  "975": "assets/football/Nakuru Bucks.jpg",
  "835": "assets/football/LSA.png",
  "457": "assets/football/RE UNION.png",
  "871": "assets/football/ROYAL SOCCER.png",
  "487": "assets/football/ROYAL UNITED.png",
  "287": "assets/football/SS ASSAD.png",
  "55": "assets/football/TANDAZA.png",
  "1029": "assets/football/Trans Nzoia FC.png",
  "545": "assets/football/UON OLYMPIC.png",
  "880": "assets/football/VALEO.png",
  "178": "assets/football/VIHIGA QUEENS (1).png",
  "58": "assets/football/VIONGOZI.png",
  "805": "assets/football/WALALAH.png",
  "174": "assets/football/WAYLIGHT.png",
  "2": "assets/football/Gor-Mahia-logo (1).png",
  "77": "assets/football/sofapaka-fc-logo-9B8F6A7B91-seeklogo.com.png",
  "149": "assets/football/Ulinzi_Stars_FC_logo.png",
  "198": "assets/football/Znoia_Sugar_F.C._logo-Photoroom.png-Photoroom.png",
  "5": "assets/football/tusker-fc-logo-2788AE204B-seeklogo.com.png",
  "595": "assets/football/Shabana_FC_(logo).png",
  "6": "assets/football/kcb football logo.png",
  "36": "assets/football/Kakamega_Homeboyz_F.C._logo.png",
  "10": "assets/football/dIrN6fqG-bBiFBAKT.png",
  "1": "assets/football/Bidco_FC_logo.gif",
  "147": "assets/football/afc-leopards-logo-1FE51F62E5-seeklogo.com.png",
  "76": "assets/football/3633358601154909bfef9f231a6df682-0-1.png",
  "84":
      "assets/football/240982120_259204366207977_7073992088656259999_n-Photoroom.png-Photoroom.png",
  "85": "assets/football/93869.png",
  "7": "assets/football/61619.png",
  "12": "assets/football/17104.png",
  "557": "assets/football/0078-Photoroom.png-Photoroom.png",
  "248": "assets/football/MARA SUGAR.png",
  "112": "assets/football/F.C._Talanta_logo-Photoroom.png-Photoroom.png",
};
